Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2025

Var
  A, B, resultado: Inteiro

Inicio
  Escreva("Digite o valor de A: ")
  Leia(A)

  Escreva("Digite o valor de B: ")
  Leia(B)

  resultado<- (A - B) * (A - B)


  Escreval("O quadrado da diferença entre A e B é: ", resultado)

Fimalgoritmo