Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2025
Var
  A, B, C, resultado: Inteiro

Inicio
  // Entrada de dados
  Escreva("Digite o valor de A: ")
  Leia(A)

  Escreva("Digite o valor de B: ")
  Leia(B)

  Escreva("Digite o valor de C: ")
  Leia(C)
  resultado<- (A * A) + (B * B) + (C * C)

  Escreval("A soma dos quadrados é: ", resultado)

Fimalgoritmo