Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2025
Var
  A, B, C, soma, resultado: Inteiro

Inicio
  Escreva("Digite o valor de A: ")
  Leia(A)

  Escreva("Digite o valor de B: ")
  Leia(B)

  Escreva("Digite o valor de C: ")
  Leia(C)

  soma<- A + B + C
  resultado<- soma * soma

  Escreval("O quadrado da soma é: ", resultado)

Fimalgoritmo