Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2025
var
   valor: inteiro
inicio
   escreva("Digite um valor entre 1 e 9: ")
   leia(valor)

   se (valor >= 1) e (valor <= 9) entao
      escreva("O valor está na faixa permitida")
   senao
      escreva("O valor está fora da faixa permitida")
   fimse
fimalgoritmo