let a = parseInt(prompt("Digite o valor de A:"));
let b = parseInt(prompt("Digite o valor de B:"));
let c = parseInt(prompt("Digite o valor de C:"));
let d = parseInt(prompt("Digite o valor de D:"));

console.log("Somas:");
console.log("A + B =", a + b);
console.log("A + C =", a + c);
console.log("A + D =", a + d);
console.log("B + C =", b + c);
console.log("B + D =", b + d);
console.log("C + D =", c + d);

console.log("Multiplicações:");
console.log("A * B =", a * b);
console.log("A * C =", a * c);
console.log("A * D =", a * d);
console.log("B * C =", b * c);
console.log("B * D =", b * d);
console.log("C * D =", c * d);